#!/usr/bin/env python3
"""Turn a route into src/script.s, the input a SCRIPT=1 build plays.

    tools/mkscript.py "FIRE@100-102,FIRE@130-132,RIGHT@150-200" [STOP [POKES]] > src/script.s

With STOP the game halts at that frame (in script_halt, interrupts still on)
so tools/c64run.py can read it at exactly that moment. POKES, as
"cat_lives=1@90,sausages_got=4@120", write a value into a variable at the
start of that frame - a screen shot of the game over wants a cat on his last
life, not a route that loses two.

The same spelling as the CPC's make check routes: a control, @, and the
frames it is held, inclusive. Frames count calls to read_controls, which is
one a frame in every loop of the game, from power on. A build with SCRIPT=1
reads nothing else, so a run is the same every time on every emulator.
"""
import sys

stop = int(sys.argv[2]) if len(sys.argv) > 2 else 65535
pokes = [p.strip() for p in (sys.argv[3] if len(sys.argv) > 3 else "").split(",") if p.strip()]

BITS = {"UP": 0x01, "DOWN": 0x02, "LEFT": 0x04, "RIGHT": 0x08, "FIRE": 0x10,
        "QUIT": 0x20, "LANG": 0x40}

out = [";; Generated by tools/mkscript.py - do not edit.",
       ";; Route: " + sys.argv[1], ""]
out += ["SCRIPT_STOP = %d" % stop, "",
        "script_controls",
        "        lda script_frame       ; the end of the route: stop here, with",
        "        cmp #<SCRIPT_STOP      ; the interrupt still running, for the",
        "        bne +                  ; harness to read the machine",
        "        lda script_frame+1",
        "        cmp #>SCRIPT_STOP",
        "        bne +",
        "script_halt",
        "        jmp script_halt",
        "+       ldx #0                 ; the pokes due this frame",
        "-       lda script_pokes+4,x", "        beq _poked",
        "        lda script_pokes,x", "        cmp script_frame", "        bne +",
        "        lda script_pokes+1,x", "        cmp script_frame+1", "        bne +",
        "        lda script_pokes+2,x", "        sta scriptp",
        "        lda script_pokes+3,x", "        sta scriptp+1",
        "        lda script_pokes+5,x", "        ldy #0", "        sta (scriptp),y",
        "+       txa", "        clc", "        adc #6", "        tax", "        bne -",
        "_poked  lda #0", "        sta ctl_scan",
        "        lda #<script_tab", "        sta scriptp",
        "        lda #>script_tab", "        sta scriptp+1",
        "_next   ldy #4", "        lda (scriptp),y", "        beq _done",
        "        ldy #0", "        lda script_frame", "        cmp (scriptp),y",
        "        iny", "        lda script_frame+1", "        sbc (scriptp),y",
        "        bcc _skip               ; not yet",
        "        ldy #2", "        lda (scriptp),y", "        cmp script_frame",
        "        iny", "        lda (scriptp),y", "        sbc script_frame+1",
        "        bcc _skip               ; over",
        "        ldy #4", "        lda (scriptp),y", "        ora ctl_scan",
        "        sta ctl_scan",
        "_skip   lda scriptp", "        clc", "        adc #5", "        sta scriptp",
        "        bcc _next", "        inc scriptp+1", "        jmp _next",
        "_done   inc script_frame", "        bne +", "        inc script_frame+1",
        "+       lda ctl_scan", "        jmp controls_store", "",
        ";; from, to, control bits", "script_tab"]
for item in sys.argv[1].split(","):
    item = item.strip()
    if not item:
        continue
    name, frames = item.split("@")
    a, b = (frames.split("-") + [frames])[:2]
    bits = 0
    for n in name.split("+"):
        bits |= BITS[n]
    out.append("        .word %d, %d" % (int(a), int(b)))
    out.append("        .byte $%02x    ; %s" % (bits, item))
out.append("        .word 0, 0")
out.append("        .byte 0")
out.append("")
out.append(";; frame, address, 1, value")
out.append("script_pokes")
for item in pokes:
    what, frame = item.split("@")
    name, value = what.split("=")
    out.append("        .word %d, %s" % (int(frame), name))
    out.append("        .byte 1, %d    ; %s" % (int(value, 0), item))
out.append("        .word 0, 0")
out.append("        .byte 0, 0")
print("\n".join(out))
