#!/usr/bin/env python3
"""Turn the font art and the UTF-8 string files into src/font.s and
src/strings.s.

    tools/mktext64.py

The same rules as the CPC's tools/mktext.py, and the same files: no literal
text in the sources, every message in both languages, Greek folded onto the
font - accents dropped, lowercase raised, and the fourteen capitals that share
a Latin shape drawn with the Latin glyph. Only Γ Δ Θ Λ Ξ Π Σ Φ Ψ Ω are drawn.

What changes is the output. The glyph index is the screen code, so the font
is a VIC character set as it stands: 8 bytes a glyph, the 5-column drawing
in bits 6-2, so it sits one pixel in from the left of its 8x8 cell. The HUD
and the footer use it in hires character mode, 40 columns; text.s also draws
it into the multicolour bitmap, one font pixel to a multicolour pixel, for
the banners.
"""

import os
import sys
import unicodedata

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_ART = os.path.join(ROOT, "assets", "font.txt")
GLYPH_W = 5
GLYPH_H = 8

GREEK_TO_LATIN = dict(zip("ΑΒΕΖΗΙΚΜΝΟΡΤΥΧ", "ABEZHIKMNOPTYX"))
LANGS = [("en", "ENGLISH"), ("el", "GREEK")]
ASM_NAMES = {
    " ": "SPACE", ".": "DOT", ",": "COMMA", "!": "BANG", "?": "QUERY",
    ":": "COLON", "-": "DASH", "'": "QUOTE", "/": "SLASH",
    "Γ": "GAMMA", "Δ": "DELTA", "Θ": "THETA", "Λ": "LAMBDA", "Ξ": "XI",
    "Π": "PI", "Σ": "SIGMA", "Φ": "PHI", "Ψ": "PSI", "Ω": "OMEGA",
}


def fold(ch):
    bare = "".join(c for c in unicodedata.normalize("NFD", ch)
                   if not unicodedata.combining(c)).upper()
    if not bare:
        return " "
    return GREEK_TO_LATIN.get(bare, bare)


def read_font():
    glyphs, name, rows = [], None, []
    for lineno, line in enumerate(open(FONT_ART, encoding="utf-8"), 1):
        line = line.rstrip("\n")
        if line.startswith(":"):
            if name is not None:
                glyphs.append((name, rows))
            name, rows = line[1:], []
            continue
        if (name is not None and len(line) == GLYPH_W
                and not set(line) - set(".#")):
            rows.append(int(line.replace(".", "0").replace("#", "1"), 2) << 2)
            continue
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        sys.exit("%s:%d: not a glyph row: %r" % (FONT_ART, lineno, line))
    glyphs.append((name, rows))
    for n, r in glyphs:
        if len(r) != GLYPH_H:
            sys.exit("%s: glyph %s has %d rows" % (FONT_ART, n, len(r)))
    return glyphs


def read_strings(path):
    out = {}
    for lineno, line in enumerate(open(path, encoding="utf-8"), 1):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, val = line.split("=", 1)
        out[key.strip()] = val.strip()
    return out


def main():
    glyphs = read_font()
    index = {(" " if n == "SPACE" else n): i for i, (n, _) in enumerate(glyphs)}
    texts = {code: read_strings(os.path.join(ROOT, "text", "loukoumas.%s.txt" % code))
             for code, _ in LANGS}
    ids = list(texts["en"])
    for code, _ in LANGS[1:]:
        if set(ids) != set(texts[code]):
            sys.exit("text/loukoumas.%s.txt: ids differ from English" % code)

    enc = {}
    for code, _ in LANGS:
        for key in ids:
            out = []
            for ch in texts[code][key]:
                g = fold(ch)
                if g not in index:
                    sys.exit("text/loukoumas.%s.txt: %s has %r, no glyph" % (code, key, ch))
                out.append(index[g])
            enc[(code, key)] = out
            if key.startswith("ROOM") and len(out) > 16:
                sys.exit("%s %s is longer than the 16 columns the HUD has" % (code, key))

    with open(os.path.join(ROOT, "src", "font.s"), "w", encoding="utf-8") as fh:
        fh.write(";; Generated by tools/mktext64.py from assets/font.txt - do not edit.\n")
        fh.write(";; A VIC character set: the glyph index is the screen code.\n\n")
        for i, (n, _) in enumerate(glyphs):
            fh.write("GL_%-7s = %d\n" % (ASM_NAMES.get(n, n), i))
        fh.write("GLYPH_COUNT = %d\n\nfont\n" % len(glyphs))
        for n, rows in glyphs:
            fh.write("        .byte %s    ; %s\n"
                     % (",".join("$%02x" % r for r in rows), ASM_NAMES.get(n, n)))
        fh.write("font_end\n")

    with open(os.path.join(ROOT, "src", "strings.s"), "w", encoding="utf-8") as fh:
        fh.write(";; Generated by tools/mktext64.py from text/loukoumas.*.txt - do not edit.\n")
        fh.write(";; Length-prefixed runs of screen codes.\n\n")
        for i, (code, name) in enumerate(LANGS):
            fh.write("LANG_%s = %d    ; %s\n" % (code.upper(), i, name))
        fh.write("LANG_COUNT = %d\n\n" % len(LANGS))
        for i, key in enumerate(ids):
            fh.write("MSG_%-10s = %d\n" % (key, i))
        fh.write("MSG_COUNT = %d\n\n" % len(ids))
        for code, _ in LANGS:
            fh.write("msgtab_%s_lo .byte %s\n" % (code, ",".join(
                "<str_%s_%s" % (code, k) for k in ids)))
            fh.write("msgtab_%s_hi .byte %s\n" % (code, ",".join(
                ">str_%s_%s" % (code, k) for k in ids)))
        fh.write("lang_lo .byte %s\n" % ",".join("<msgtab_%s_lo" % c for c, _ in LANGS))
        fh.write("lang_hi .byte %s\n" % ",".join(">msgtab_%s_lo" % c for c, _ in LANGS))
        fh.write("        .cerror msgtab_en_hi-msgtab_en_lo != MSG_COUNT\n\n")
        for code, _ in LANGS:
            for key in ids:
                d = enc[(code, key)]
                fh.write("str_%s_%s .byte %d%s\n" % (code, key, len(d),
                         "".join(",%d" % v for v in d)))
    print("mktext64: %d glyphs, %d messages" % (len(glyphs), len(ids)), file=sys.stderr)


if __name__ == "__main__":
    main()
