;; Generated by tools/mkmusic64.py from the CPC's loukmus.asm - do not edit.
;; Per voice: note, lines; note 0 is a rest, $ff loops.

MUSIC_SPEED = 5             ; ticks a line, as on the CPC

;; SID frequencies of the notes the song uses, PAL.
music_notes_lo .byte 0, <1873, <2103, <2360, <2807, <3536, <4205, <5298, <5613, <7072, <8410, <10596, <11226, <14144, <16820
music_notes_hi .byte 0, >1873, >2103, >2360, >2807, >3536, >4205, >5298, >5613, >7072, >8410, >10596, >11226, >14144, >16820

music_v1
        .byte  5,   2     ; note 44
        .byte  6,   2     ; note 47
        .byte 14,   2     ; note 71
        .byte 12,   4     ; note 64
        .byte 11,   2     ; note 63
        .byte 13,   2     ; note 68
        .byte 12,   2     ; note 64
        .byte  8,   2     ; note 52
        .byte 12,   2     ; note 64
        .byte  8,   2     ; note 52
        .byte 12,   4     ; note 64
        .byte  4,   2     ; note 40
        .byte  8,   2     ; note 52
        .byte 12,   2     ; note 64
        .byte  1,   2     ; note 33
        .byte  7,   2     ; note 51
        .byte  8,   2     ; note 52
        .byte  9,   4     ; note 56
        .byte 11,   2     ; note 63
        .byte  8,   2     ; note 52
        .byte 10,   2     ; note 59
        .byte  5,   2     ; note 44
        .byte 11,   2     ; note 63
        .byte 10,   2     ; note 59
        .byte 12,   4     ; note 64
        .byte  2,   2     ; note 35
        .byte  8,   2     ; note 52
        .byte 13,   2     ; note 68
        .byte  8,   2     ; note 52
        .byte  6,   2     ; note 47
        .byte 14,   2     ; note 71
        .byte 12,   4     ; note 64
        .byte  3,   2     ; note 37
        .byte 13,   2     ; note 68
        .byte 12,   2     ; note 64
        .byte  8,   2     ; note 52
        .byte  6,   2     ; note 47
        .byte 10,   2     ; note 59
        .byte  9,   4     ; note 56
        .byte  9,   2     ; note 56
        .byte 14,   2     ; note 71
        .byte 12,   2     ; note 64
        .byte  1,   2     ; note 33
        .byte 11,   2     ; note 63
        .byte  8,   2     ; note 52
        .byte  9,   4     ; note 56
        .byte  1,   2     ; note 33
        .byte  8,   2     ; note 52
        .byte 10,   2     ; note 59
        .byte  2,   2     ; note 35
        .byte  6,   2     ; note 47
        .byte  8,   2     ; note 52
        .byte  7,   4     ; note 51
        .byte 11,   2     ; note 63
        .byte  5,   2     ; note 44
        .byte 13,   2     ; note 68
        .byte $ff

music_v2
        .byte  0,  64     ; rest
        .byte  0,  64     ; rest
        .byte $ff
