;; Generated by tools/mksprite64.py from assets/sprites.txt and
;; assets/art/sprite - do not edit.
;;
;; A frame is: body pointer, overlay pointer, body colour, overlay
;; colour. Shared colours are black ($D025) and white ($D026).

SPR_CAT_STAND_W      = 12
SPR_CAT_STAND_H      = 20
SPR_CAT_WALK1_W      = 12
SPR_CAT_WALK1_H      = 20
SPR_CAT_WALK2_W      = 12
SPR_CAT_WALK2_H      = 20
SPR_CAT_ROLL_W       = 12
SPR_CAT_ROLL_H       = 14
SPR_CAT_FLAT_W       = 12
SPR_CAT_FLAT_H       = 10
SPR_ROBOT_W          = 12
SPR_ROBOT_H          = 14
SPR_CANARY_W         = 8
SPR_CANARY_H         = 12
SPR_DOG_W            = 10
SPR_DOG_H            = 16
SPR_PIGEON_W         = 8
SPR_PIGEON_H         = 10
SPR_WASP_W           = 6
SPR_WASP_H           = 8
SPR_BALL_W           = 6
SPR_BALL_H           = 12
SPR_PLANE_W          = 10
SPR_PLANE_H          = 8
SPR_MOP_W            = 8
SPR_MOP_H            = 16
SPR_BLOB_W           = 8
SPR_BLOB_H           = 10
SPR_SYRINGE_W        = 10
SPR_SYRINGE_H        = 6
SPR_BAT_W            = 12
SPR_BAT_H            = 8
SPR_STRAY_W          = 12
SPR_STRAY_H          = 14

SPRITE_BLOCKS        = 47
FRM_SIZE             = 4

frm_cat_stand    .byte  1,  2,  7, 10
frm_cat_walk1    .byte  1,  3,  7, 10
frm_cat_walk2    .byte  1,  4,  7, 10
frm_cat_roll     .byte  5,  6,  7, 10
frm_cat_flat     .byte  7,  8,  7, 10
frm_robot        .byte  9, 10, 12,  2
frm_robot_l      .byte  9, 10, 12,  2
frm_canary       .byte 11, 12,  7, 10
frm_canary_l     .byte 13, 14,  7, 10
frm_dog          .byte 15, 16,  8,  2
frm_dog_l        .byte 17, 18,  8,  2
frm_pigeon       .byte 19, 20, 12, 10
frm_pigeon_l     .byte 21, 22, 12, 10
frm_wasp         .byte 23,  0,  7,  0
frm_wasp_l       .byte 24,  0,  7,  0
frm_ball         .byte 25,  0,  7,  0
frm_ball_l       .byte 26,  0,  7,  0
frm_plane        .byte 27,  0, 12,  0
frm_plane_l      .byte 28,  0, 12,  0
frm_mop          .byte 29, 30,  3,  7
frm_mop_l        .byte 31, 32,  3,  7
frm_blob         .byte 33, 34, 13,  5
frm_blob_l       .byte 35, 36, 13,  5
frm_syringe      .byte 37, 38, 12,  3
frm_syringe_l    .byte 39, 40, 12,  3
frm_bat          .byte 41, 42,  4, 10
frm_bat_l        .byte 41, 42,  4, 10
frm_stray        .byte 43, 44, 12, 13
frm_stray_l      .byte 45, 46, 12, 13
