;; Generated by tools/mksprite64.py from assets/sprites.txt and
;; assets/art/sprite - do not edit.
;;
;; A frame is: body pointer, overlay pointer, body colour, overlay
;; colour. Shared colours are black ($D025) and white ($D026).

SPR_CAT_STAND_W      = 12
SPR_CAT_STAND_H      = 20
SPR_CAT_WALK1_W      = 12
SPR_CAT_WALK1_H      = 20
SPR_CAT_WALK2_W      = 12
SPR_CAT_WALK2_H      = 20
SPR_CAT_ROLL_W       = 12
SPR_CAT_ROLL_H       = 14
SPR_CAT_FLAT_W       = 12
SPR_CAT_FLAT_H       = 10
SPR_ROBOT_W          = 12
SPR_ROBOT_H          = 14
SPR_CANARY_W         = 8
SPR_CANARY_H         = 12
SPR_DOG_W            = 10
SPR_DOG_H            = 16
SPR_PIGEON_W         = 8
SPR_PIGEON_H         = 10
SPR_WASP_W           = 6
SPR_WASP_H           = 8
SPR_BALL_W           = 6
SPR_BALL_H           = 12
SPR_PLANE_W          = 10
SPR_PLANE_H          = 8
SPR_MOP_W            = 8
SPR_MOP_H            = 16
SPR_BLOB_W           = 8
SPR_BLOB_H           = 10
SPR_SYRINGE_W        = 10
SPR_SYRINGE_H        = 6
SPR_BAT_W            = 12
SPR_BAT_H            = 8
SPR_STRAY_W          = 12
SPR_STRAY_H          = 14

SPRITE_BLOCKS        = 75
FRM_SIZE             = 4

frm_cat_stand    .byte SPR_PTR0+1, SPR_PTR0+2,  7, 10
frm_cat_walk1    .byte SPR_PTR0+1, SPR_PTR0+3,  7, 10
frm_cat_walk2    .byte SPR_PTR0+1, SPR_PTR0+4,  7, 10
frm_cat_roll     .byte SPR_PTR0+5, SPR_PTR0+6,  7, 10
frm_cat_flat     .byte SPR_PTR0+7, SPR_PTR0+8,  7, 10
frm_robot        .byte SPR_PTR0+9, SPR_PTR0+10, 12,  2
frm_robot_l      .byte SPR_PTR0+9, SPR_PTR0+10, 12,  2
frm_robot2       .byte SPR_PTR0+11, SPR_PTR0+10, 12,  2
frm_robot2_l     .byte SPR_PTR0+11, SPR_PTR0+10, 12,  2
frm_canary       .byte SPR_PTR0+12, SPR_PTR0+13,  7, 10
frm_canary_l     .byte SPR_PTR0+14, SPR_PTR0+15,  7, 10
frm_canary2      .byte SPR_PTR0+16, SPR_PTR0+17,  7, 10
frm_canary2_l    .byte SPR_PTR0+18, SPR_PTR0+19,  7, 10
frm_dog          .byte SPR_PTR0+20, SPR_PTR0+21,  8,  2
frm_dog_l        .byte SPR_PTR0+22, SPR_PTR0+23,  8,  2
frm_dog2         .byte SPR_PTR0+24, SPR_PTR0+21,  8,  2
frm_dog2_l       .byte SPR_PTR0+25, SPR_PTR0+23,  8,  2
frm_pigeon       .byte SPR_PTR0+26, SPR_PTR0+27, 12, 10
frm_pigeon_l     .byte SPR_PTR0+28, SPR_PTR0+29, 12, 10
frm_pigeon2      .byte SPR_PTR0+30, SPR_PTR0+27, 12, 10
frm_pigeon2_l    .byte SPR_PTR0+31, SPR_PTR0+29, 12, 10
frm_wasp         .byte SPR_PTR0+32, 0,  7,  0
frm_wasp_l       .byte SPR_PTR0+33, 0,  7,  0
frm_wasp2        .byte SPR_PTR0+34, 0,  7,  0
frm_wasp2_l      .byte SPR_PTR0+35, 0,  7,  0
frm_ball         .byte SPR_PTR0+36, 0,  7,  0
frm_ball_l       .byte SPR_PTR0+37, 0,  7,  0
frm_ball2        .byte SPR_PTR0+38, 0,  7,  0
frm_ball2_l      .byte SPR_PTR0+39, 0,  7,  0
frm_plane        .byte SPR_PTR0+40, 0, 12,  0
frm_plane_l      .byte SPR_PTR0+41, 0, 12,  0
frm_plane2       .byte SPR_PTR0+42, 0, 12,  0
frm_plane2_l     .byte SPR_PTR0+43, 0, 12,  0
frm_mop          .byte SPR_PTR0+44, SPR_PTR0+45,  3,  7
frm_mop_l        .byte SPR_PTR0+46, SPR_PTR0+47,  3,  7
frm_mop2         .byte SPR_PTR0+48, SPR_PTR0+49,  3,  7
frm_mop2_l       .byte SPR_PTR0+50, SPR_PTR0+51,  3,  7
frm_blob         .byte SPR_PTR0+52, SPR_PTR0+53, 13,  5
frm_blob_l       .byte SPR_PTR0+54, SPR_PTR0+55, 13,  5
frm_blob2        .byte SPR_PTR0+56, SPR_PTR0+57, 13,  5
frm_blob2_l      .byte SPR_PTR0+58, SPR_PTR0+59, 13,  5
frm_syringe      .byte SPR_PTR0+60, SPR_PTR0+61, 12,  3
frm_syringe_l    .byte SPR_PTR0+62, SPR_PTR0+63, 12,  3
frm_syringe2     .byte SPR_PTR2+0, SPR_PTR0+61, 12,  3
frm_syringe2_l   .byte SPR_PTR2+1, SPR_PTR0+63, 12,  3
frm_bat          .byte SPR_PTR2+2, SPR_PTR2+3,  4, 10
frm_bat_l        .byte SPR_PTR2+2, SPR_PTR2+3,  4, 10
frm_bat2         .byte SPR_PTR2+4, SPR_PTR2+3,  4, 10
frm_bat2_l       .byte SPR_PTR2+4, SPR_PTR2+3,  4, 10
frm_stray        .byte SPR_PTR2+5, SPR_PTR2+6, 12, 13
frm_stray_l      .byte SPR_PTR2+7, SPR_PTR2+8, 12, 13
frm_stray2       .byte SPR_PTR2+9, SPR_PTR2+6, 12, 13
frm_stray2_l     .byte SPR_PTR2+10, SPR_PTR2+8, 12, 13
